# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          # Installing incompatible latexindent perl dependencies via apk
          apk --no-cache add \
              perl-log-log4perl \
              perl-log-dispatch \
              perl-namespace-autoclean \
              perl-specio \
              perl-unicode-linebreak
        
          # Installing remaining latexindent perl dependencies via cpan
          apk --no-cache add curl wget make
          ls /usr/share/texmf-dist/scripts/latexindent
          curl -L https://cpanmin.us/ -o /usr/local/bin/cpanm && \
              chmod +x /usr/local/bin/cpanm
          cpanm -n App::cpanminus
          cpanm -n File::HomeDir
          cpanm -n Params::ValidationCompiler
          cpanm -n YAML::Tiny
          cpanm -n Unicode::GCString
          
          ./build.sh

    - uses: matheusalbino/git-commit@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: "style: format the code by latexindent"
